storybookjs/eslint-plugin-storybook

README.md, docs/rules/await-interactions.md, docs/rules/use-storybook-testing-library.md, lib/configs/addon-interactions.js, lib/configs/recommended.js, lib/rules/await-interactions.js, lib/rules/use-storybook-expect.js, lib/utils/ast.js, package.json, tests/lib/rules/await-interactions.js, yarn.lock
Issue: #
one more for addon-interactions
=> add await-interactions rule

lib/rules/no-redundant-story-name.js, tests/lib/rules/no-redundant-story-name.js
Issue: #
Fix scenario where users use CSF3 + spread operator
=> fix no-redundant-story-name

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/test.yml
Issue: N/A
This PR adds a test step to the Github actions 
=> chore(ci): add test workflow

lib/rules/await-interactions.ts, lib/rules/csf-component.ts, lib/rules/default-exports.ts, lib/rules/hierarchy-separator.ts, lib/rules/meta-inline-properties.ts, lib/rules/no-redundant-story-name.ts, lib/rules/no-stories-of.ts, lib/rules/no-title-property-in-meta.ts, lib/rules/prefer-pascal-case.ts, tests/lib/rules/await-interactions.test.ts, tests/lib/rules/csf-component.test.ts, tests/lib/rules/default-exports.test.ts, tests/lib/rules/hierarchy-separator.test.ts, tests/lib/rules/meta-inline-properties.test.ts, tests/lib/rules/no-redundant-story-name.test.ts, tests/lib/rules/no-stories-of.test.ts, tests/lib/rules/no-title-property-in-meta.test.ts, tests/lib/rules/prefer-pascal-case.test.ts, tests/lib/rules/use-storybook-expect.test.ts, tests/lib/rules/use-storybook-testing-library.test.ts
Issue: N/A
Added a couple more test cases as well as TODO comments for cases we should/could support
=> Chore: add typescript examples to test

lib/rules/no-redundant-story-name.ts, tests/lib/rules/no-redundant-story-name.test.ts
=> no-redundant-story-name: add CSF2 support

lib/rules/prefer-pascal-case.ts, tests/lib/rules/prefer-pascal-case.test.ts
=> prefer-pascal-case: ignore __namedExportsOrder

lib/configs/addon-interactions.ts, lib/configs/csf.ts, lib/configs/recommended.ts, tools/update-configs.ts
Issue: N/A
The regex from #40 was not supported, so I just simplified things as much as possible. Thanks @ndelangen !
=> simplify override file regex

README.md
Issue: N/A
Added a section about overriding rules in the README
=> docs(README): add overrides section

docs/rules/use-storybook-expect.md, lib/rules/use-storybook-expect.ts, tests/lib/rules/use-storybook-expect.test.ts
I'm not entirely positive which repo is the correct one, but the code and tests use @storybook/jest, so that's the one I'm guessing is correct. 
=> Unify documentation to use @storybook/jest

README.md
storybook/defaul-exports => storybook/default-exports
Issue: #
=> Update README.md spelling error, one letter.

README.md, lib/configs/addon-interactions.ts, lib/configs/csf.ts, lib/configs/recommended.ts, tools/update-configs.ts
Issue: #59 
The JSX extension was added to the list.
=> fix: support jsx extension

.github/workflows/linear-export.yml
=> chore: add linear to gh actions

lib/rules/default-exports.ts
=> fix default-exports rule name

lib/rules/story-exports.ts
Issue: N/A
The story-exports highlight was done on the entire file which was weird.
Now it highlights the first non-import statement:
Might still be a little weird, but better than before for sure. @shilman Thoughts?
=> fix(story-exports): stop highlighting the entire code on error

lib/rules/no-uninstalled-addons.ts, tests/lib/rules/no-uninstalled-addons.test.ts
=> no-uninstalled-addons: improve local addons filter

docs/rules/await-interactions.md
=> docs: add async

package.json
Issue: #
<details>
<summary>📦 Published PR as canary version: <code>0.7.1--canary.151.8c31ca9.0</code></summary>
<br />
```bash
npm install eslint-plugin-storybook@0.7.1--canary.151.8c31ca9.0
yarn add eslint-plugin-storybook@0.7.1--canary.151.8c31ca9.0
```
</details>
=> fix release

package.json, pnpm-lock.yaml
=> Bump CSF version to remove lodash transitive dep

tsconfig.build.json
Issue: #172
This PR adds types to the eslint plugin, as they have become essential for flat config projects
=> Generate Typescript types for flat configs

.github/workflows/release.yml, .github/workflows/test.yml, package.json
Upgrade the build process 
<details>
<summary>📦 Published PR as canary version: <code>0.11.3--canary.191.cb8e720.0</code></summary>
<br />
```bash
npm install eslint-plugin-storybook@0.11.3--canary.191.cb8e720.0
yarn add eslint-plugin-storybook@0.11.3--canary.191.cb8e720.0
```
</details>
=> Upgrade corepack/pnpm
