storybookjs/eslint-plugin-storybook

CONTRIBUTING.md
README.md
lib/configs/csf-strict.js
lib/rules/meta-inline-properties.js
tools/utils/rules.js

Issue: #
Add a flag to exclude a rule (temporarily hopefully) from being published in the lint config

add exclude rule flag

---

lib/rules/use-storybook-testing-library.js
tests/lib/rules/use-storybook-testing-library.js

Issue: #15
Fixed handling of
```js
import userEvent from '@testing-library/user-event';
import userEvent, { foo, bar as Bar } from '@testing-library/user-event';
```

Fix use-storybook-testing-library default export handling

---

lib/rules/use-storybook-expect.ts
tests/lib/rules/use-storybook-expect.ts

add support for CSF3 notation in use-storybook-expect

---

lib/rules/await-interactions.ts
tests/lib/rules/await-interactions.test.ts

Issue: N/A
The following should be valid
```
await expect(foo).toBe(bar);
```
This required fixing the logic around awaiting expectations!

await-interactions: Fix bad expect matchers

---

lib/rules/default-exports.ts
tests/lib/rules/default-exports.test.ts

Issue: N/A
The rule `default-exports` was not allowing to be disabled. By changing the target node it is now possible

default-exports: target first non-import nodes when reporting

---

lib/rules/prefer-pascal-case.ts
lib/utils/index.ts
package.json
tests/lib/rules/prefer-pascal-case.test.ts
yarn.lock

Issue: #
Added a check for non-story exports so that they are not impacted by the prefer-pascal-case rule

prefer-pascal-case: add non-story exports check

---

lib/rules/hierarchy-separator.ts
tests/lib/rules/hierarchy-separator.test.ts

Issue: N/A
The highlighting of the rule was being applied to the entire meta. Now it does only for the title node:

hierarchy-separator: fix node highlight

---

lib/rules/no-title-property-in-meta.ts
tests/lib/rules/no-title-property-in-meta.test.ts

Issue: N/A
Before, the highlighting was done in the entire meta. Now it's only in the title node:
I also fixed an issue where if the code is like this:
```js
export default {
title: 'Button',
component: Button
}
```
would be fixed to this, leaving a comma:
```js
export default {
,
component: Button
}
```

no-title-property-in-meta: fix dangling comma and highlighting

---

lib/rules/csf-component.ts
lib/rules/default-exports.ts
tests/lib/rules/default-exports.test.ts

Issue: N/A
```
import { MyComponent } from './MyComponent'
```
=>
```
import { MyComponent } from './MyComponent'
export { component: MyComponent }
```

Add autofix heuristics for default-exports rule

---

lib/rules/hierarchy-separator.ts
tests/lib/rules/hierarchy-separator.test.ts

Issue: N/A
Regarding hierarchy-separators, the dot can be used for normal names and adds confusion. Given it's a pretty old convention I think it's safe to just ignore the dot and check only for pipe instead.

hierarchy-separator: remove dot from checkings

---

lib/rules/prefer-pascal-case.ts
tests/lib/rules/prefer-pascal-case.test.ts

Issue: N/A
Stories that start with underscore should be ignored as they might be written like that to avoid name collision with the components

prefer-pascal-case: ignore stories that start with underscore

---

lib/rules/default-exports.ts
lib/rules/prefer-pascal-case.ts
tests/lib/rules/default-exports.test.ts
tests/lib/rules/prefer-pascal-case.test.ts

Issue: N/A
Both `default-export` and `prefer-pascal-case` rules should not be applied to older formats (storiesOf)

ignore storiesOf in default-export and prefer-pascal-case

---

README.md
docs/rules/story-exports.md
lib/configs/csf.ts
lib/configs/recommended.ts
lib/rules/story-exports.ts
tests/lib/rules/story-exports.test.ts
tools/generate-rule.ts

Issue: #42
Added a new rule `story-exports` to enforce defining at least one named export in a story file.

Rule: add story-exports

---

README.md
lib/rules/await-interactions.ts
lib/rules/default-exports.ts
lib/rules/hierarchy-separator.ts
lib/rules/no-redundant-story-name.ts
lib/rules/no-title-property-in-meta.ts
lib/rules/prefer-pascal-case.ts
lib/rules/story-exports.ts
lib/rules/use-storybook-expect.ts
lib/rules/use-storybook-testing-library.ts
tools/generate-rule.ts

Issue: #54 
- All fixable rules now define hasSuggestions
- `yarn generate-rule` improved to reflect that new change

Fix: define hasSuggestions to all fixable rules

---

lib/rules/story-exports.ts
lib/utils/index.ts
tests/lib/rules/story-exports.test.ts

Issue: #57 
Fixed a bug where the story-exports rule gave a false negative because it did not check for exports from an export list, only from inline export declarations.

extend story-exports rule to support export lists, fixes #57

---

lib/rules/prefer-pascal-case.ts
lib/rules/story-exports.ts
tests/lib/rules/prefer-pascal-case.test.ts
tests/lib/rules/story-exports.test.ts

Issue: #65 
Rules that access the `includeStories`/`excludeStories` properties from Meta and throw an error (e.g. using dynamic properties) will be gracefully handled now.

fix: gracefully handle dynamic values in non-story exports configuration

---

lib/rules/prefer-pascal-case.ts
lib/utils/index.ts

Issue: #75
Changed the AST utils imports to use the public API so they'll work with both the old `@typescript-eslint/experimental-utils` and newly renamed `@typescript-eslint/utils` packages.

Fix ast-utils import

---

package.json

Issue: N/A
<details>
<summary>📦 Published PR as canary version: <code>0.5.7--canary.82.b92f058.0</code></summary>
<br />
```bash
npm install eslint-plugin-storybook@0.5.7--canary.82.b92f058.0
yarn add eslint-plugin-storybook@0.5.7--canary.82.b92f058.0
```
</details>

chore: remove release label restriction

---

CONTRIBUTING.md
lib/rules/csf-component.ts
lib/rules/hierarchy-separator.ts
lib/rules/meta-inline-properties.ts
lib/rules/no-title-property-in-meta.ts
tests/lib/rules/hierarchy-separator.test.ts
tests/lib/rules/no-title-property-in-meta.test.ts

Issue: #78
- add optional chaining to the handling of `MetaObjectExpression` properties to prevent type exception when not of type `Property`.
- add a few test cases to help validate more syntactically valid cases
- minor text update to CONTRIBUTING.md

fix: add optional chaining to object property key

---

lib/rules/await-interactions.ts
tests/lib/rules/await-interactions.test.ts

Issue: #86
in existing use-cases of the `await-interactions` rule, the code is assumed to be valid when the `CallExpression` node is the immediate child of an `AwaitExpression` node.
> `await FirstStory.play(context);` → AwaitExpression > CallExpression > …
> `await FirstStory.play!(context);` → AwaitExpression > CallExpression > TSNonNullExpression > …
to support an expression with an optional chain, the logic to determine if the expression was properly awaited now checks if the _parent of the parent_ of the `CallExpression` node is an `AwaitExpression`.
> `await FirstStory.play?.(context);` → AwaitExpression > ChainExpression > CallExpression > …

fix: support ChainExpression in await-interactions rule

---

lib/rules/default-exports.ts
tests/lib/rules/default-exports.test.ts

Issue: N/A
`default-exports` rule now autofixes even if the component is not imported. In that case, it will add an empty export like:
```js
export default {}
```

feat(default-exports): add autofix even if component name is not found

---

.eslintrc.js
lib/rules/await-interactions.ts
lib/rules/context-in-play-function.ts
lib/rules/csf-component.ts
lib/rules/default-exports.ts
lib/rules/hierarchy-separator.ts
lib/rules/meta-inline-properties.ts
lib/rules/no-redundant-story-name.ts
lib/rules/no-stories-of.ts
lib/rules/no-title-property-in-meta.ts
lib/rules/prefer-pascal-case.ts
lib/rules/story-exports.ts
lib/rules/use-storybook-expect.ts
lib/rules/use-storybook-testing-library.ts
lib/utils/ast.ts
lib/utils/create-storybook-rule.ts
lib/utils/index.ts
package.json
tests/lib/rules/hierarchy-separator.test.ts
tests/lib/rules/no-title-property-in-meta.test.ts
tools/update-configs.ts
tools/update-rules-list.ts
tools/utils/categories.ts
tools/utils/docs.ts
tools/utils/rules.ts
tsconfig.json
yarn.lock

Added some types and removed obsolete "any" type assertions by replacing them through stronger types
<details>
<summary>📦 Published PR as canary version: <code>0.5.11--canary.89.28723b8.0</code></summary>
<br />
```bash
npm install eslint-plugin-storybook@0.5.11--canary.89.28723b8.0
yarn add eslint-plugin-storybook@0.5.11--canary.89.28723b8.0
```
</details>

Increase type safety

---

README.md
docs/rules/no-uninstalled-addons.md
lib/configs/addon-interactions.ts
lib/configs/csf.ts
lib/configs/recommended.ts
lib/rules/no-uninstalled-addons.ts
tests/lib/rules/no-uninstalled-addons.test.ts
tools/update-configs.ts

feat(no-uninstalled-addons): add uninstalled plugin rule

---

lib/rules/no-uninstalled-addons.ts
tests/lib/rules/no-uninstalled-addons.test.ts

Issue: #97
This PR adds a fix for addons which are locally registered such as:
```js
// .storybook/main.js
module.exports = {
addons: [
'./my-addon/preset.cjs', // <-- ignored in the checks
'@storybook/addon-essentials'
]
}
```

fix(no-uninstalled-addons): ignore local addons

---

docs/rules/no-uninstalled-addons.md
lib/configs/addon-interactions.ts
lib/configs/csf.ts
lib/configs/recommended.ts
lib/rules/no-uninstalled-addons.ts

Issue: #101
The `no-uninstalled-addons` feature had an issue where it was assuming that the `package.json` of which the addon dependencies are installed was always in the root, and for some projects that was not true. For that scenario, the rule now provides an option to specify the exact path of the package.json:
```
module.exports = {
rules: {
'storybook/no-uninstalled-addons': ['error', { packageJsonLocation: './custom-folder/package.json' }],
},
}
```

feat(no-uninstalled-addons): add option for a custom package.json location

---

package.json
tests/lib/rules/no-uninstalled-addons.test.ts

Issue: #103 
`ts-dedent` was used in a rule but was defined as dev-dependency. This PR fixes that
<details>
<summary>📦 Published PR as canary version: <code>0.6.3--canary.104.2956130.0</code></summary>
<br />
```bash
npm install eslint-plugin-storybook@0.6.3--canary.104.2956130.0
yarn add eslint-plugin-storybook@0.6.3--canary.104.2956130.0
```
</details>

deps: move ts-dedent to dependencies

---

lib/rules/story-exports.ts
tests/lib/rules/story-exports.test.ts

Issue: N/A
The `story-exports` rule now detects whether you are using `includeStories/excludeStories` and provides a more helpful message in case there are not exported stories. A possible scenario is you have a typo in your `includeStories` which will result in Storybook not including it:
```js
export default {
title: 'Button',
includeStories: ['myStory'], // <-- notice the lowercase m, which won't match with the story name
};
export const MyStory = {};
```
>The file should have at least one story export. Make sure the includeStories/excludeStories you defined are correct, otherwise Storybook will not use any stories for this file.'
The `story-exports` rule now detects whether you are using …

story-exports: provide better feedback when using filters

---

lib/configs/addon-interactions.ts
lib/configs/csf.ts
lib/configs/recommended.ts
lib/rules/no-redundant-story-name.ts
lib/rules/prefer-pascal-case.ts
lib/rules/use-storybook-testing-library.ts
lib/utils/index.ts
tsconfig.json

Issue: #106 
i was getting crashes in vs code without this check.
if you want you could also enable the typescript `noUncheckedIndexedAccess` option to more easily catch similar issues.

fix: add declaration checks to avoid destructuring undefined

---

lib/rules/no-uninstalled-addons.ts
tests/lib/rules/no-uninstalled-addons.test.ts

Running the tests fails on Windows because of the way paths are being resolved inside the `no-uninstalled-addons` rule. 
* Replaced the relevant `/` occurrences with `path.sep` which should just work for both POSIX and Windows.
*  Updated the tests accordingly.

fix(no-uninstalled-addons) Support Windows paths

---

.eslintrc.js
lib/rules/await-interactions.ts
lib/rules/context-in-play-function.ts
lib/rules/csf-component.ts
lib/rules/hierarchy-separator.ts
lib/rules/meta-inline-properties.ts
lib/rules/no-title-property-in-meta.ts
lib/rules/no-uninstalled-addons.ts
lib/rules/prefer-pascal-case.ts
lib/rules/story-exports.ts
lib/rules/use-storybook-expect.ts
lib/rules/use-storybook-testing-library.ts
lib/types/index.ts
lib/utils/create-storybook-rule.ts
lib/utils/index.ts
package.json
tools/update-configs.ts
tools/update-rules-list.ts
tools/utils/categories.ts
yarn.lock

* Removed `plugin:node/recommended` from `.eslintrc.js` because it caused ESLint to raise a lot of `node/no-unsupported-features/es-syntax` errors in TypeScript files. I'm not sure why it was actually used, please let me know!
* Explicitly set ESLint parser to `@typescript-eslint/parser` so that it actually processes TypeScript files.
* Added `@typescript-eslint` `devDependencies` for better compatibility between ESLint and TypeScript (it disables conflicted rules e.g. `no-unused-args` when actually defining a type, etc.)
* Refined a bit some typing for the `no-uninstalled-addons` rule so that is is slightly more precise
* Ran the autofix in the whole project and manually fixed remaining warnings/errors
* Made sure to provide adequate fallbacks when using optional chaining after the above …

chore: fix ESLint and TypeScript issues

---

lib/utils/index.ts
tools/generate-rule.ts

Issue: N/A
General improvements to the `yarn generate-rule` command :)

improve rule template

---

docs/rules/no-uninstalled-addons.md
lib/rules/no-uninstalled-addons.ts
tests/lib/rules/no-uninstalled-addons.test.ts

Issue: #
Added the `ignore` option in the `no-uninstalled-addons` rule.

feat: allow ignore option in no-uninstalled-addons

---

lib/rules/use-storybook-expect.ts
tests/lib/rules/use-storybook-expect.test.ts

This PR allows imports from `@storybook/test`, an experimental package that provides similar utilities than `@storybook/jest`.

use-storybook-expect: allow storybook/test imports

---

lib/rules/no-uninstalled-addons.ts
tests/lib/rules/no-uninstalled-addons.test.ts

Issue: #
no-uninstalled-addons now works with 2 additional export ways 
([as shown in the docs](https://storybook.js.org/docs/react/configure/overview)) 
```
const config: StorybookConfig = {
...
};
export default config;
```
&
```
export default {
addons: [
...
],
} satisfies StorybookConfig;
```

no-uninstalled-addons: support satisfies operator and default reexport

---

lib/configs/addon-interactions.ts
lib/configs/csf-strict.ts
lib/configs/csf.ts
lib/configs/recommended.ts

Closes: https://github.com/storybookjs/storybook/issues/21115
I chatted with @valentinpalkovic and we concluded that instead of writing an automigration adding code that in neither case looks "quite right", we considered maybe adding an exception to the config exposed by the plugin, which turns off the problems reported from `react-hooks` eslint plugin.
<details>
<summary>📦 Published PR as canary version: <code>0.7.0--canary.149.b9dd4e1.0</code></summary>
<br />
```bash
npm install eslint-plugin-storybook@0.7.0--canary.149.b9dd4e1.0
yarn add eslint-plugin-storybook@0.7.0--canary.149.b9dd4e1.0
```
</details>

Disable rule of hooks in stories files

---

docs/rules/meta-inline-properties.md
docs/rules/use-storybook-expect.md
docs/rules/use-storybook-testing-library.md

Issue: #
Some of the rules have a 'Further Reading' section that don't provide any additional reading materials. I simply removed them in this PR.
I considered modifying the template in generate-rule.ts too, but I can't think of a good way to do it since the writer will have to manually delete the section header anyway, if they have nothing to write for a given optional section.

Remove uninformative 'Further Reading' sections from rule docs

---

tools/generate-rule.ts

Issue:  none
`generate-rule` of npm scripts is useful, but I think some points are improvable.
So, I tweaked these.
N/A
N/A (only internal source code changes)

Tweak `generate-rule`

---

README.md
docs/rules/no-uninstalled-addons.md

Since the `.eslintignore` documentation has been moved from https://eslint.org/docs/latest/user-guide/configuring/ignoring-code to https://eslint.org/docs/latest/use/configure/ignore-deprecated, I have updated README and `no-uninstalled-addons.md` accordingly.

chore: Update the link for eslintignore doc

---

README.md
package.json

Issue: #185 
Updates the peer dependency version range for `eslint`.

fix(peer-deps): update eslint version range to `>=8`

---

lib/rules/default-exports.ts
tests/lib/rules/default-exports.test.ts

Issue: #
<details>
<summary>📦 Published PR as canary version: <code>0.11.3--canary.187.1af857a.0</code></summary>
<br />
```bash
npm install eslint-plugin-storybook@0.11.3--canary.187.1af857a.0
yarn add eslint-plugin-storybook@0.11.3--canary.187.1af857a.0
```
</details>

default-exports: Support CSF factory style meta

---

package.json
pnpm-lock.yaml

Remove typescript as a peer dependency, update dev typescript to 5.8.
Users will still need to provide typescript themselves, but any competent package manager will let the user know this.

fix(peer-deps): Add support for typescript 5.8

---

docs/rules/context-in-play-function.md
lib/rules/context-in-play-function.ts
tests/lib/rules/context-in-play-function.test.ts

Issue: #162
Added checks for self-referencing properties.

fix: allows self-referencing context in play function
